name: 2Dor3D
channels:
  - defaults
  - conda-forge
  - openbabel
dependencies:
  - python==3.7.*
  - numpy==1.19.*
  - pandas==1.*
  - scikit-learn==0.23.*
  - matplotlib==3.*
  - openbabel==2.4.*
  - rdkit==2020.03.*
  - ase==3.19.*
  - mordred==1.2.*
  - corner==2.1.*
  - kombine==0.8.*
  - pymatgen==2020.12.31
  - modal==0.4.*
#  - tensorflow>2
  - jedi<0.18  # 0.18 currently incompatible with Jupyter
  - tqdm
  - jupyterlab
  - psutil
  - pytest
  - pip
  - pip:
    - git+https://github.com/qmlcode/qml.git@develop
    - dscribe==0.4.0
    - matminer==0.6.*
    - tensorflow>2
